### ISSUE TITLE
Position of "mark as read" and position of "unsubscribe" in the dashboard

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_github#14] opened 2020-11-05 21:53 UTC
a screenshot will be easier to understand :)
![image](https://user-images.githubusercontent.com/16205280/98300565-bb7eeb00-1fb9-11eb-8122-7abaaec9b4d6.png)

**Comment by eneiluj** [comment] 2020-11-08 03:03
This is related with the vue components. I can't do much about it in this app. It does not happen if the widget is placed in the first row so I guess this is caused by the drag-n-drop grid display component. I wonder if it's possible to solve this in nc-vue "Actions" component... I tried with latest nc-vue release and the problem is still there, too bad. To be continued.

Thanks for the bug report.

**Comment by eneiluj** [comment] 2021-01-18 16:26
Good news, there is a simple CSS solution for this. Fix is included in v0.0.17 which is out there. Could you confirm it now works on your side too?

Make sure you reload the dashboard with CTRL+F5 after the app update. It will increase the chances to reload the style stuff.

Cheers

**Comment by Ludovicis** [comment] 2021-01-19 11:24
Hi Eneiluj, it's perfect !!! Thanks,

**Closed** 2021-01-19 11:25 UTC
